[tool.black]
line-length = 100
target-version = ['py310']

[tool.ruff]
line-length = 88
target-version = "py310"
select = ["E", "F", "I"]  # I: import order
ignore = ["E501", "W291"]
fixable = ["ALL"]
